import { Locale, i18n } from "@/i18n-config";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { getDictionary } from "@/get-dictionary";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "InmoGolf Bonalba",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: {
  params: { lang: Locale };
  children: React.ReactNode;
}) {
  const dict = await getDictionary(params.lang);

  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col">
          <Header params={params} dict={dict} />
          <main className="relative grow bg-zinc-50">{children}</main>
          <Footer params={params} dict={dict} />
        </div>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  const locales = i18n.locales;

  const params = locales!.flatMap((locale) => {
    return {
      lang: locale,
    };
  });

  return params;
}
